.PHONY: verify

verify:
	gofmt -w $$(find . -name '*.go' -not -path './.git/*')
	git diff --check -- .
	go vet -mod=readonly ./...
	go test -mod=readonly -race -cover ./...
	go build -mod=readonly ./...
